import { FlatCompat } from "@eslint/eslintrc";
import { defineConfig, globalIgnores } from "eslint/config";
import boundaries from "eslint-plugin-boundaries";
import jsxA11y from "eslint-plugin-jsx-a11y";

/**
 * Flat config. Three layers on top of the Next.js defaults:
 *
 * 1. `jsx-a11y` — accessibility is a stated requirement, so the linter enforces
 *    it rather than leaving it to review.
 * 2. `boundaries` — the architecture is only "feature-based" if the boundaries
 *    are mechanical. This turns a cross-feature import into a build failure.
 * 3. Local rules codifying decisions made elsewhere in the codebase.
 *
 * `eslint-config-next@15` still ships in eslintrc format only, so it comes in
 * through `FlatCompat` rather than a direct import.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = defineConfig([
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "supabase/.temp/**",
    "playwright-report/**",
    "test-results/**",
    "src/types/database.ts", // generated by `pnpm gen:types`
  ]),

  {
    plugins: { "jsx-a11y": jsxA11y },
    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
      // Base UI primitives forward props through `render`, so the plugin often
      // can't see the underlying element. Downgraded to avoid false positives.
      "jsx-a11y/no-autofocus": ["warn", { ignoreNonDOM: true }],
      "jsx-a11y/heading-has-content": "off",
    },
  },

  {
    plugins: { boundaries },
    settings: {
      "boundaries/include": ["src/**/*"],
      /**
       * Element descriptors are folders: each pattern names one architectural
       * layer, and every file beneath it belongs to that layer. `partialMatch:
       * false` anchors the pattern to the project root, so `src/lib` cannot be
       * satisfied by an incidental `.../lib/` further down the tree.
       *
       * Order matters — `elements-single-match` makes classification exclusive,
       * so the narrower descriptors (`src/components/ui`) must precede the
       * broader ones (`src/components`), and the `src` catch-all comes last so
       * it only picks up loose root files such as `middleware.ts`.
       */
      "boundaries/elements-single-match": true,
      "boundaries/elements": [
        { type: "app", pattern: "src/app", partialMatch: false },
        {
          type: "feature",
          pattern: "src/features/*",
          capture: ["feature"],
          partialMatch: false,
        },
        { type: "ui", pattern: "src/components/ui", partialMatch: false },
        { type: "components", pattern: "src/components", partialMatch: false },
        { type: "hooks", pattern: "src/hooks", partialMatch: false },
        { type: "services", pattern: "src/services", partialMatch: false },
        { type: "lib", pattern: "src/lib", partialMatch: false },
        { type: "utils", pattern: "src/utils", partialMatch: false },
        { type: "types", pattern: "src/types", partialMatch: false },
        { type: "root", pattern: "src", partialMatch: false },
      ],
    },
    rules: {
      /**
       * The dependency direction, top to bottom: `app` composes features;
       * features use shared infrastructure but never each other's internals;
       * `lib`/`utils`/`types` are leaves that depend on nothing above them.
       *
       * Two constraints are worth calling out:
       *
       * - A feature is reachable from outside only through its `index.ts`.
       *   Importing `features/resume/store/resume-store` couples the caller to
       *   an implementation detail; importing `features/resume` couples it to a
       *   contract. Expressed as `fileInternalPath` on the target.
       * - `ui` (vendored shadcn primitives) may not depend on `components`.
       *   Primitives that reach back up into our shared layer stop being
       *   replaceable when shadcn regenerates them.
       *
       * Policies are last-write-wins, so the broad layer allowances come after
       * the feature-specific ones they must not override.
       */
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          policies: [
            {
              from: { element: { types: { anyOf: ["app", "root"] } } },
              allow: {
                to: {
                  element: {
                    types: {
                      anyOf: [
                        "app",
                        "root",
                        "ui",
                        "components",
                        "hooks",
                        "services",
                        "lib",
                        "utils",
                        "types",
                      ],
                    },
                  },
                },
              },
            },
            {
              from: { element: { types: { anyOf: ["app", "root"] } } },
              allow: { to: { element: { type: "feature", fileInternalPath: "index.ts" } } },
            },
            {
              // Same feature: free movement inside its own folder.
              from: { element: { type: "feature" } },
              allow: {
                to: {
                  element: {
                    type: "feature",
                    captured: { feature: "{{ from.element.captured.feature }}" },
                  },
                },
              },
            },
            {
              from: { element: { type: "feature" } },
              allow: { to: { element: { type: "feature", fileInternalPath: "index.ts" } } },
            },
            {
              from: { element: { type: "feature" } },
              allow: {
                to: {
                  element: {
                    types: {
                      anyOf: ["ui", "components", "hooks", "services", "lib", "utils", "types"],
                    },
                  },
                },
              },
            },
            {
              from: { element: { type: "components" } },
              allow: {
                to: {
                  element: {
                    types: { anyOf: ["components", "ui", "hooks", "lib", "utils", "types"] },
                  },
                },
              },
            },
            {
              from: { element: { type: "ui" } },
              allow: { to: { element: { types: { anyOf: ["ui", "lib", "utils", "types"] } } } },
            },
            {
              from: { element: { type: "hooks" } },
              allow: {
                to: { element: { types: { anyOf: ["hooks", "lib", "utils", "types"] } } },
              },
            },
            {
              from: { element: { type: "services" } },
              allow: {
                to: { element: { types: { anyOf: ["services", "lib", "utils", "types"] } } },
              },
            },
            {
              from: { element: { type: "lib" } },
              allow: { to: { element: { types: { anyOf: ["lib", "utils", "types"] } } } },
            },
            {
              from: { element: { type: "utils" } },
              allow: { to: { element: { types: { anyOf: ["utils", "types"] } } } },
            },
            {
              from: { element: { type: "types" } },
              allow: { to: { element: { type: "types" } } },
            },
          ],
        },
      ],
    },
  },

  {
    rules: {
      // Unused vars are usually a real mistake; a leading underscore is the
      // explicit way to say "intentionally ignored".
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },

  {
    /**
     * Vendored shadcn primitives. These three rules only produce false positives
     * here because the primitives are prop pass-throughs: `Label` renders a bare
     * `<label>` and receives `htmlFor` from the caller, and `InputGroupAddon`'s
     * click handler forwards focus to the input it wraps — the same
     * click-to-focus affordance a `<label>` has, and the input is already
     * keyboard reachable, so a keyboard listener on the wrapper would be dead
     * code. Association is enforced where it can actually be seen: `FormField`
     * wires `htmlFor` to a generated control id.
     */
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "jsx-a11y/label-has-associated-control": "off",
      "jsx-a11y/click-events-have-key-events": "off",
      "jsx-a11y/no-noninteractive-element-interactions": "off",
    },
  },

  {
    // Tests reach past the public surface on purpose: a unit test for a store or
    // a scorer has to import the thing it tests, not the feature's barrel.
    files: ["**/*.test.{ts,tsx}", "e2e/**/*.ts", "**/*.config.{ts,mts,mjs}"],
    rules: {
      "boundaries/dependencies": "off",
      "no-console": "off",
    },
  },
]);

export default eslintConfig;
